# This file was generated by GoReleaser. DO NOT EDIT.
cask "kidwords" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "49e8abd62e68751a4cd936e8ca1b63c03551f57cbaebc3f36f0d7a8a59d6dba3"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_darwin_arm64.zip",
        verified: "github.com/dkotik/kidwords/",
        using: :homebrew_curl
    end
    on_intel do
      sha256 "f15d2c3611dfbd0f0509348cd77d42da6434c2c9fe1d8231443b62f7b4c2a0c7"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_darwin_amd64.zip",
        verified: "github.com/dkotik/kidwords/",
        using: :homebrew_curl
    end
  end
  on_linux do
    on_arm do
      sha256 "fed1a368d7c987ffe63e56acb1212b4f9a3c80d13a85e4ce94a86fd61fe98712"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_linux_arm64.zip",
        verified: "github.com/dkotik/kidwords/",
        using: :homebrew_curl
    end
    on_intel do
      sha256 "a7479fc436a5cdade4b2183f1f6d9b091005ad863cf5287ce714731879c3452a"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_linux_amd64.zip",
        verified: "github.com/dkotik/kidwords/",
        using: :homebrew_curl
    end
  end

  name "kidwords"
  desc "Durable and accessible paper key encoding that children can use."
  homepage "https://github.com/dkotik/kidwords"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kidwords"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kidwords"]
    end
  end

  # No zap stanza required
end
