# This file was generated by GoReleaser. DO NOT EDIT.
cask "kidwords" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "8ab79dcd9e6a8d723073384a8279b5053ee2500d1102dca306c752669aa8dc5e"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_darwin_arm64.zip",
        using: :homebrew_curl
    end
    on_intel do
      sha256 "7b3dcf474ef665ff41fdc3238c6bbbb2b9d3d277c316d0fb7c931e4680e197ee"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_darwin_amd64.zip",
        using: :homebrew_curl
    end
  end
  on_linux do
    on_arm do
      sha256 "a68bd8d8795f74040dafc3f452721165f5a8950fb41bc0b3610d842eafeff2f7"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_linux_arm64.zip",
        using: :homebrew_curl
    end
    on_intel do
      sha256 "03487752501f986faa5009cb09dc46c0a60c0e113baea47f23cc13d1180abee8"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_linux_amd64.zip",
        using: :homebrew_curl
    end
  end

  name "kidwords"
  desc "Durable and accessible paper key encoding that children can use."
  homepage "https://github.com/dkotik/kidwords"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kidwords"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kidwords"]
    end
  end

  # No zap stanza required
end
