# This file was generated by GoReleaser. DO NOT EDIT.
cask "kidwords" do
  version "0.0.9"

  on_macos do
    on_intel do
      sha256 "fede57a39341b5b2a6299a89882a1e7ff3b7fb6958eb92b1968c90a6516cb795"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_darwin_amd64.zip",
        verified: "github.com/dkotik/kidwords/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "8fa0244a83c3878eedc9919d07b580b8f3a0d3ab74680889eb9c206b7fe157c6"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_darwin_arm64.zip",
        verified: "github.com/dkotik/kidwords/",
        using: :homebrew_curl
    end
  end

  on_linux do
    on_intel do
      sha256 "349ec6d963e9dd6f6476565b1f0e10df2e775c719d8d5404d08850f22a724181"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_linux_amd64.zip",
        verified: "github.com/dkotik/kidwords/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "ce6bbb90b25bff32f8c6909b9a5c4b3fd17106ffd666cf366bfb652670ebfb2f"
      url "https://github.com/dkotik/kidwords/releases/download/v#{version}/kidwords_#{version}_linux_arm64.zip",
        verified: "github.com/dkotik/kidwords/",
        using: :homebrew_curl
    end
  end

  name "kidwords"
  desc "Durable and accessible paper key encoding that children can use."
  homepage "https://github.com/dkotik/kidwords"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kidwords"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kidwords"]
    end
  end

  # No zap stanza required

end
