# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdcoach" do
  version "0.0.9"

  on_macos do
    on_arm do
      sha256 "6e11ce79c55224b41c4460789dcce1b8d1d4c98bd1366f9fb4972c033ffe3e20"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_darwin_arm64.zip",
        using: :homebrew_curl
    end
    on_intel do
      sha256 "b6565c95fb2c65bd1fbcf950048ffb85e5301ce487094cca52e7f0bc92483525"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_darwin_amd64.zip",
        using: :homebrew_curl
    end
  end
  on_linux do
    on_arm do
      sha256 "0e7c27ea0097675fe7336afb89e6a9a442d0e10347fb43bfe2c94f4ec539f5e7"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_linux_arm64.zip",
        using: :homebrew_curl
    end
    on_intel do
      sha256 "df3cce6ebe8d0fd89e358dc005282c634619320fec6b402dd3343ed87aa22873"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_linux_amd64.zip",
        using: :homebrew_curl
    end
  end

  name "mdcoach"
  desc "Generate slide presentations with speaker notes from Markdown files."
  homepage "https://github.com/dkotik/mdcoach"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdcoach"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdcoach"]
    end
  end

  # No zap stanza required
end
