# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdcoach" do
  version "0.0.8"

  on_macos do
    on_arm do
      sha256 "1c98c17090a90fb0d931e89e91dccdcdf6efaa2df54769be94ccfa35e6ca5144"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_darwin_arm64.zip",
        using: :homebrew_curl
    end
    on_intel do
      sha256 "ee64249310fc9f29af7254ec9c970968ca0f4080bed522734bb634d440bb15dc"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_darwin_amd64.zip",
        using: :homebrew_curl
    end
  end
  on_linux do
    on_arm do
      sha256 "3ec952663873fe900bb0dac9176ef93d2ef197d5fed610c4b1acabea82b86c0e"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_linux_arm64.zip",
        using: :homebrew_curl
    end
    on_intel do
      sha256 "f96ca335b34902a3047816e7b0070b1ea06debf05d0def990de386ac14e3bf6b"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_linux_amd64.zip",
        using: :homebrew_curl
    end
  end

  name "mdcoach"
  desc "Generate slide presentations with speaker notes from Markdown files."
  homepage "https://github.com/dkotik/mdcoach"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdcoach"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdcoach"]
    end
  end

  # No zap stanza required
end
