# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdcoach" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "6a9b713f05aaca54682b949b2ffa4f8c104dab02f7c871f55788416ed40bb105"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_darwin_amd64.zip",
        verified: "github.com/dkotik/mdcoach/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "1cd7605fd01d62acb9e9fc08aec1c118e6366b74c495c37aaeccec27f9d89200"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_darwin_arm64.zip",
        verified: "github.com/dkotik/mdcoach/",
        using: :homebrew_curl
    end
  end

  on_linux do
    on_intel do
      sha256 "8b8abd87bf04ff648603d6d5eec0df02373b6a8a7970797219966c31c1c8504b"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_linux_amd64.zip",
        verified: "github.com/dkotik/mdcoach/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "094cccb010c32bfbca944d5d5efca59c08bb1e43bf954bd57243f5f423a06ef2"
      url "https://github.com/dkotik/mdcoach/releases/download/v#{version}/mdcoach_#{version}_linux_arm64.zip",
        verified: "github.com/dkotik/mdcoach/",
        using: :homebrew_curl
    end
  end

  name "mdcoach"
  desc "Generate slide presentations with speaker notes from Markdown files."
  homepage "https://github.com/dkotik/mdcoach"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdcoach"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdcoach"]
    end
  end

  # No zap stanza required

end
