# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdsend" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "622f799ea4e47229615ecadef0e278ce875de0f47a9079ef8e0ddeb857893c89"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_darwin_amd64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "4e76b1e53e5f1ea93668488e54ef2e5b1591d6ac757d15f233d78ff69178f66a"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_darwin_arm64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
  end

  on_linux do
    on_intel do
      sha256 "04174157a0e65dd1518cc5d4d75720520213195af831ff1c79a69460e592c0fe"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_linux_amd64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "5a6c95f6252db85f07f5fd21e695868b953ad3cad6fec721a651e429ab8ccdc8"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_linux_arm64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
  end

  name "mdsend"
  desc "Send markdown files as MIME-encoded electronic mail."
  homepage "https://github.com/dkotik/mdsend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdsend"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdsend"]
    end
  end

  # No zap stanza required

end
