# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdsend" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "afdb56218a553de66d860ca04431edda678a541bdc8d7dc485047de3954a765f"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_darwin_amd64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "db5368c8e4443ae22712340ac3586b3c338dd3b8fa6ace2a046606a12da7b997"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_darwin_arm64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
  end

  on_linux do
    on_intel do
      sha256 "227c7284fb435091e9d07100b45a197d196120306cc7552e358daa74d1b4b9ff"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_linux_amd64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "77a26168106f77545b94fffe8d8beac5ebc6c0ca98ab21b705446ea75ea6a97a"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_linux_arm64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
  end

  name "mdsend"
  desc "Send markdown files as MIME-encoded electronic mail."
  homepage "https://github.com/dkotik/mdsend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdsend"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdsend"]
    end
  end

  # No zap stanza required

end
