# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdsend" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "6888f16dcfbf1b4c16ef2238fa4a8506f7021c2cc63ed6dbc8ed3a7595ba32bc"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_darwin_amd64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "0ea5605e7751d0e4669a9f0aab775335726e1d488b7e5302e9cecad96c5c2581"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_darwin_arm64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
  end

  on_linux do
    on_intel do
      sha256 "0ec68cfd68a5016da4f27447686b9b025c37f3d0ee0cd48612087607574de8b3"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_linux_amd64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "473d62181e513209615269e32bccf301ed0ad273057795f96dc5a6b0a99b43b2"
      url "https://github.com/dkotik/mdsend/releases/download/v#{version}/mdsend_#{version}_linux_arm64.zip",
        verified: "github.com/dkotik/mdsend/",
        using: :homebrew_curl
    end
  end

  name "mdsend"
  desc "Send markdown files as electronic mail. Maintain mailing lists as templated text files."
  homepage "https://github.com/dkotik/mdsend"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdsend"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdsend"]
    end
  end

  # No zap stanza required

end
