# This file was generated by GoReleaser. DO NOT EDIT.
cask "pageseo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "869b78d3e8215954fd5f025d9a1cbd8de22135e645722f7a1cde21e5ca7b3c15"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_darwin_amd64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "e85eed30c4332342588c67abc4c2229ed75e3e8128452a56bf65461616dcb001"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_darwin_arm64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
  end

  on_linux do
    on_intel do
      sha256 "9faeabfc374f59066c892edc1c2e7e753dd86874be1a14e4403f55bc9a5a804c"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_linux_amd64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "2359dacd28099fca2b4dc10dee6c532e82bb8a038863cdaeffe39288e8f19f2e"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_linux_arm64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
  end

  name "pageseo"
  desc "Send markdown files as electronic mail. Maintain mailing lists as templated text files."
  homepage "https://github.com/dkotik/pageseo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pageseo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pageseo"]
    end
  end

  # No zap stanza required

end
