# This file was generated by GoReleaser. DO NOT EDIT.
cask "pageseo" do
  version "1.1.5"

  on_macos do
    on_intel do
      sha256 "d5457c6f30a62a3de6e21721babea90a2e071a38ed70b3f35b671f6c8aa0d6f8"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_darwin_amd64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "540ba28f722b3f85bd3e3cc5f1b9a7653d148084027b6037d9a69d05d31ddae8"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_darwin_arm64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
  end

  on_linux do
    on_intel do
      sha256 "d2c895b266954ce4b381b85ac6f86b01ac64c5bd580b38264de141ef7239648e"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_linux_amd64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "3ec8d2e10602bcc56f470a666c4779342eb1d40de37d037712de5b48a7e13ff3"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_linux_arm64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
  end

  name "pageseo"
  desc "HTML page search engine optimization test and utility suite."
  homepage "https://github.com/dkotik/pageseo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pageseo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pageseo"]
    end
  end

  # No zap stanza required

end
