# This file was generated by GoReleaser. DO NOT EDIT.
cask "pageseo" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "f63495409a3518553386a7199553aeb33fc522dd8945db128e0970212ac15968"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_darwin_amd64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "67c5313fbfcae8b3fe2b691dce44ea5fca5fe25cf702e34cd8624c98ccea5890"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_darwin_arm64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
  end

  on_linux do
    on_intel do
      sha256 "4bd3596b04b1e48bd3de23a539decf98f90c19de488849344b7d875f676248c7"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_linux_amd64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
    on_arm do
      sha256 "5913d57dc5a5499888a4c6a72f247ce1c1bcbb577be955e295928fe5411b6dba"
      url "https://github.com/dkotik/pageseo/releases/download/v#{version}/pageseo_#{version}_linux_arm64.zip",
        verified: "github.com/dkotik/pageseo/",
        using: :homebrew_curl
    end
  end

  name "pageseo"
  desc "HTML page search engine optimization test and utility suite."
  homepage "https://github.com/dkotik/pageseo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pageseo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pageseo"]
    end
  end

  # No zap stanza required

end
