# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdsend < Formula
  desc "Send markdown files as MIME-encoded electronic mail."
  homepage "https://github.com/dkotik/mdsend"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/dkotik/mdsend/releases/v0.0.3/mdsend_0.0.3_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1fe5e620fb348d28619a5eac1858e1de06840a879bbfda2167ec069258b9276a"

      def install
        bin.install "mdsend"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/dkotik/mdsend/releases/v0.0.3/mdsend_0.0.3_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8afeba6e40d594181ceae6f30d6c5324c33ab63bfcb510ed0e4b0fb3df178137"

      def install
        bin.install "mdsend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/dkotik/mdsend/releases/v0.0.3/mdsend_0.0.3_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "74724e1713e491c4c9ff759dac7d0e6370e5e73f48e282de871d16843a2b169b"

      def install
        bin.install "mdsend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/dkotik/mdsend/releases/v0.0.3/mdsend_0.0.3_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "baae687a472246f869417d83d2a8325e28bce25f90bd50e81d1a2a2f41f8feb9"

      def install
        bin.install "mdsend"
      end
    end
  end

  test do
    system "#{bin}/mdsend --version"
  end
end
